# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Services Our
  description: Services Our
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  id: our
  title: Our Service
  data:
    - logo: /images/iconlogo.png
      img: /images/our1.png
      title: HAIRCUTS & STYLE
      button: Book now
      type:
        - name: HAIRCUT AND STYLE
          price: $42 - $78+
        - name: HAIRCUT AND STYLE
          price: $42 - $78+
        - name: HAIRCUT AND STYLE
          price: $42 - $78+
        - name: HAIRCUT AND STYLE
          price: $42 - $78+
    - logo: /images/iconlogo.png
      img: /images/our1.png
      title: HAIRCUTS & STYLE
      button: Book now
      type:
        - name: HAIRCUT AND STYLE
          price: $42 - $78+
        - name: HAIRCUT AND STYLE
          price: $42 - $78+
        - name: HAIRCUT AND STYLE
          price: $42 - $78+
        - name: HAIRCUT AND STYLE
          price: $42 - $78+
    - logo: /images/iconlogo.png
      img: /images/our1.png
      title: HAIRCUTS & STYLE
      button: Book now
      type:
        - name: HAIRCUT AND STYLE
          price: $42 - $78+
        - name: HAIRCUT AND STYLE
          price: $42 - $78+
        - name: HAIRCUT AND STYLE
          price: $42 - $78+
        - name: HAIRCUT AND STYLE
          price: $42 - $78+
    - logo: /images/iconlogo.png
      img: /images/our1.png
      title: HAIRCUTS & STYLE
      button: Book now
      type:
        - name: HAIRCUT AND STYLE
          price: $42 - $78+
        - name: HAIRCUT AND STYLE
          price: $42 - $78+
        - name: HAIRCUT AND STYLE
          price: $42 - $78+
        - name: HAIRCUT AND STYLE
          price: $42 - $78+
  background: "#FFF"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id:
    type: text
    label: ID Section
  title:
    type: text
    label: Title
  description:
    type: text
    label: Description
  subtitle[*].text:
    type: text
    label: text
  image:
    type: image
    label: Image
  image_alt:
    type: text
    label: Image Alt
