# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Gallery Section
  description: Gallery Section
  icon: "cottage"

# Defines the structure of this component, as well as the default values
blueprint:
  id: gallery
  title: Our Gallery
  subtitle: Better choice<br/>to create new lifestyle
  infor: Stay informed with our newsletter.
  button_booking:
    - button_desktop: Booking now
    - button_mobile: Subcribe now
  time:
    - morning: Morning
    - afternoon: Afternoon
  title_infor_update: YOUR INFORMATION
  date_infor_update: Thursday 10-26-2023
  time_infor_update: 16:30
  button_update: CONFIRM APPOINTMENT
  title_modal: BOOKING AN APPOINTMENT
  listMenu:
    - item: Eyelash
    - item: Waxing
    - item: Nail Art
    - item: Skin
  listImage:
    - image: /images/gallery1.png
      title: Eyelash
      subtitle: Designed by Roxy
      image_alt:
    - image: /images/gallery2.png
      title: Eyelash
      subtitle: Designed by Roxy
      image_alt:
    - image: /images/gallery3.png
      title: Eyelash
      subtitle: Designed by Roxy
      image_alt:
    - image: /images/gallery1.png
      title: Eyelash
      subtitle: Designed by Roxy
      image_alt:
    - image: /images/gallery2.png
      title: Eyelash
      subtitle: Designed by Roxy
      image_alt:
    - image: /images/gallery3.png
      title: Eyelash
      subtitle: Designed by Roxy
      image_alt:
    - image: /images/gallery1.png
      title: Eyelash
      subtitle: Designed by Roxy
      image_alt:
    - image: /images/gallery2.png
      title: Eyelash
      subtitle: Designed by Roxy
      image_alt:
    - image: /images/gallery3.png
      title: Eyelash
      subtitle: Designed by Roxy
      image_alt:
    - image: /images/gallery1.png
      title: Eyelash
      subtitle: Designed by Roxy
      image_alt:
    - image: /images/gallery2.png
      title: Eyelash
      subtitle: Designed by Roxy
      image_alt:
    - image: /images/gallery3.png
      title: Eyelash
      subtitle: Designed by Roxy
      image_alt:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  id:
    type: text
    label: ID Section
  title:
    type: text
    label: Title
  subtitle:
    type: markdown
    label: Subtitle
  infor:
    type: text
    label: Infor
  listMenu[*].item:
    type: text
    label: Title Menu
  listImage[*].image:
    type: image
    label: Image
  listImage[*].image_alt:
    type: text
    label: Image Alt
  listImage[*].title:
    type: text
    label: Title Image
  listImage[*].subtitle:
    type: text
    label: Subtitle Image
  button_booking[*].button_desktop:
    type: text
    label: Title Button Desktop
  button_booking[*].button_mobile:
    type: text
    label: Title Button Mobile
  time[*].morning:
    type: text
    label: Title Time
  time[*].afternoon:
    type: text
    label: Title Time
  title_infor_update:
    type: text
    label: Title Infor Update 
  date_infor_update:
    type: text
    label: Date Infor Update 
  time_infor_update:
    type: number
    label: Time Infor Update
  button_update:
    type: text
    label: Button Update
  title_modal:
    type: text
    label: Title Modal